#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" <<-EOSQL
    CREATE USER $FRONTLOGS_DB_USER WITH PASSWORD '$FRONTLOGS_DB_PASSWORD';
    CREATE DATABASE $FRONTLOGS_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $FRONTLOGS_DB_USER TO $FRONTLOGS_DB_USER;
    CREATE DATABASE $FRONTLOGS_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $FRONTLOGS_DB_NAME TO $FRONTLOGS_DB_USER;
EOSQL
